$schema: https://railway.app/railway.schema.json
services:
  web:
    build:
      builder: dockerfile
    deploy:
      startCommand: python src/web_server.py
    port: 8000
    healthcheck:
      path: /
